discourse/discourse-prometheus

lib/demon.rb

This is a temporary and hacky solution until deploying of Zeitwerk for core Discourse. In that PR https://github.com/discourse/discourse/pull/8098 demon base class was modified for Zeitwerk
The goal is here is the ability to safely merge that code before move Discourse to Zeitwerk.

FIX: Demon base class depending on autoloader

---

lib/middleware/metrics.rb
plugin.rb
spec/middleware/metrics_spec.rb

`prometheus_trusted_ip_whitelist_regex` is deprecated and replaced with `prometheus_trusted_ip_allowlist_regex`

FIX: Use prometheus_trusted_ip_allowlist_regex

---

lib/internal_metric/process.rb
lib/reporter/process.rb
spec/lib/reporter/process_spec.rb

Two new metrics are introduced:
active_record_failover_count: "Count of ActiveRecord databases in a failover state",
redis_failover_count: "Count of Redis servers in a failover state"
This leans on counts from the rails_failover gem.

FEATURE: Add per-process metrics for Discourse readonly states

---

lib/collector.rb
lib/internal_metric/global.rb
spec/lib/reporter/global_spec.rb

discourse_readonly_sites: Count of sites currently in readonly mode, grouped by the relevant key from Discourse::READONLY_KEYS

FEATURE: Add global metrics for Discourse readonly state

---

lib/internal_metric/global.rb
spec/lib/internal_metric/global_spec.rb

Because we expose `Discourse.stats` in core, there is nothing really to stop something writing directly to the `missing_s3_uploads` guage even if the S3 inventory is disabled. Now, when `enable_s3_inventory` is false we do not expose the `missing_s3_uploads` metric for the associated DB.

FIX: When S3 inventory disabled for a DB don't collect missing uploads metric

---

bin/collector
lib/collector_demon.rb
lib/global_reporter_demon.rb
plugin.rb

Running a thread which makes postgres connections in the master unicorn
process can lead to unexpected failures in forked processes.

FIX: Run the global reporter in its own demon process

---

lib/global_reporter_demon.rb
lib/reporter/global.rb
plugin.rb

- FIX: Ensure the global reporter demon exits cleanly
- DEV: Move to new register_demon_process plugin API
This allows the unicorn master to take care of starting and monitoring the demon. It also means the demon is started after all app/plugin initialization has completed.
This change is backwards compatible.

Demon improvements

---

lib/collector.rb
lib/internal_metric/global.rb
spec/lib/internal_metric/global_spec.rb

The previous `git ref-list --count` metric does not work with shallow
clones of Discourse. With the latest Discourse base image, the number
returned will not be useful for comparisons.
This commit replaces the `version` metric with a `version_info` metric.
This always has a value of `1`. It has a `revision` label containing
the current discourse core commit hash, and a `version` label containing
the human-friendly `Discourse::VERSION::STRING`.
Output looks like
```
discourse_version_info{revision="35a2da32f29856e4d048d6856b825ed9d7a988c6",version="2.7.0.beta2"} 1
```

FIX: Replace `version` integer metric with new `version_info` metric

---

lib/middleware/metrics.rb
spec/middleware/metrics_spec.rb

The regular expression to detect private IP addresses did not always
detect them successfully. Changed to use ruby's in-built
IPAddr.new(ip_address).private? method instead which does the same thing
but covers all cases.

SECURITY: /metrics accessible from public IP addresses

---

.discourse-compatibility
lib/internal_metric/global.rb
spec/lib/internal_metric/global_spec.rb

Should be merged after: https://github.com/discourse/discourse/pull/12688.

DEV: Compatibility with Discourse on Rails 6.1

---

README.md
lib/reporter/global.rb
plugin.rb
spec/lib/reporter/global_spec.rb
spec/support/null_metric.rb

Other plugins can add custom global metrics by adding them to a DiscoursePluginRegistry filtered register.

FEATURE: Collect custom global metrics.

---

lib/reporter/web.rb

`require_dependency` is only required in rare situations and should
really be considered internal to Rails. A simple `require` would suffice
here.

DEV: Remove constant already initialized warning.

---

lib/collector.rb
lib/internal_metric/global.rb
spec/lib/internal_metric/global_spec.rb
spec/lib/reporter/global_spec.rb

- Adds a new 'type' label to the redis_master_available and redis_slave_available metrics. If a message-bus redis is configured, this will differentiate between the 'main' and 'message-bus' redis instances
- Updates names of Redis and Postgres metrics:
`redis_master_available` -> `redis_primary_available`
`redis_slave_available` -> `redis_replica_available`
`postgres_master_available` -> `postgres_primary_available`
Support for the old names is maintained for now with a deprecation notice in the metric description

FEATURE: Add message-bus redis metrics; deprecate master/slave names

---

plugin.rb

Zeitwerk might not have taken over when plugin.rb file is loaded and
that causes the requires to fail on Rails 7 when we try to autoload a
constant before Zeitwerk takes over.

DEV: Require plugin files after initialization.

---

lib/collector.rb
lib/internal_metric/process.rb
lib/reporter/process.rb
spec/lib/collector_spec.rb
spec/lib/reporter/process_spec.rb

This new metric allows monitoring of failed scheduled job runs
Previously we had no visibility outside of logs for this information

FEATURE: add the scheduled_job_failures metric

---

lib/collector.rb
lib/internal_metric/job.rb
lib/job_metric_initializer.rb
plugin.rb
spec/job_metric_initializer_spec.rb
spec/lib/collector_spec.rb
spec/lib/internal_metric/base_spec.rb

Giving metrics a baseline of 0 ensures that prometheus functions like `increase()` function correctly.

FEATURE: Initialize metrics at 0 for all known jobs

---

lib/collector.rb
spec/lib/collector_spec.rb

Allows for the differentiation between cached/non-cached and successful
(2xx HTTP response code) and unsuccessful request.

FEATURE: Add cache and success label to web duration metrics 

---

lib/collector.rb
spec/lib/collector_spec.rb

All these timing metrics are highly affected by the anonymous cache. Tracking anon and regular users in the same metric can be somewhat misleading, because the site will appear to get faster during anonymous traffic spikes, while in reality it could be getting slower for the (arguably more important) logged-in users

FEATURE: Label all timing metrics with logged_in boolean

---

lib/collector.rb
lib/internal_metric/web.rb
spec/lib/collector_spec.rb

For now, `content_type` label can either be `json`, `html` or `other` to limit the cardinality of the metrics.

FEATURE: Add `content_type` label to web performance metrics

---

lib/collector.rb
spec/lib/collector_spec.rb

The metric is useful when introducing a change that would only affect
the performance of application code. For example, upgrading Ruby
versions or enabling YJIT in Ruby. With this metric, we are able to
isolate and analyse the performance of the application code as a result
of those changes.

FEATURE: Introduce `http_application_duration_seconds` summary metric

---

lib/collector.rb
lib/internal_metric/web.rb
spec/lib/collector_spec.rb
spec/lib/internal_metric/web_spec.rb

Why this change?
These metrics being introduced will allow us to understand the impact
that Ruby's GC has during a request and allows us to tune our GC in
production.

DEV: Introduce `http_gc_duration_seconds`, `http_gc_(major|minor)_count` metrics

---

lib/collector.rb
spec/lib/collector_spec.rb

Excluding gc duration from application duration metric allows us to
stack the various duration graphs to make up the total duration of a
request.

FIX: Exclude gc duration from application duration metric

---

lib/internal_metric/process.rb
lib/reporter/process.rb
spec/lib/reporter/process_spec.rb

Why this change?
`GC.latest_gc_info(:major_by)` returns the reason that triggered the
last major GC run. This information is useful when doing GC tuning since
it will give us an idea on what to tune in order to have the greatest
impact.

FEATURE: Instrument reason for the trigger of last major GC

---

lib/internal_metric/process.rb

> A gauge is a metric that represents a single numerical value that can arbitrarily go up and down.
> A counter is a cumulative metric that represents a single monotonically increasing counter whose value can only increase or be reset to zero on restart.
Given the definition above, a counter is what we want.

DEV: `gc_major_by` should be a counter not a gauge

---

lib/collector.rb

The gauge was supposed to be renamed from pg_highest_seq to postgres_highest_sequence as part of the PR, but one place was missed
Followup to 44f22c2cb1f9b450b1f21ddba5c0bad62235e020

FIX: postgres_highest_sequence naming

---

lib/internal_metric/global.rb
spec/lib/internal_metric/global_spec.rb

Why this change?
In `Discourse::Prometheus::InternalMetric#calc_postgres_highest_sequence`, it was initially written such that
we will only query the database once every 60 seconds by setting the `postgres_highest_sequence_last_check`
class variable. However, there is a subtle bug in Rails where we were
storing a `Time` object in `@@postgres_highest_sequence_last_check` and
then subsequently using it to compare against an `Integer` which ends up
always evaluating to `false`.
```
[3] pry(main)> now = Time.now
=> 2024-01-25 06:01:07.44213925 +0800
[4] pry(main)> now >= Time.now.to_i - 60
=> false
[5] pry(main)> now.to_i >= Time.now.to_i - 60
=> true
```
Due to this bug, we end up querying all the databases every time metrics
are collected (defaults to every 5 seconds) instead of only …

PERF: Avoid hammering the database with pg sequence check queries

---

lib/reporter/process.rb
spec/lib/collector_spec.rb
spec/lib/reporter/process_spec.rb

Why this change?
Prior to this change, the `active_record_connections_count` metric is
simply a sum of all the connections for all the connection pools.
However, this metric is not helpful in a multisite environment where
there are multiple connection pools and when we need to figure out which
connection pool is holding on to a large amount of connections.

FEATURE: Add `database` label to `active_record_connections_count`

---

spec/lib/collector_spec.rb
spec/lib/reporter/process_spec.rb

The database name may not always be `discourse_test` depending on how
the tests are ran. For example, it could be `discourse_test_1` when ran
using `turbo_rspec`

DEV: Fix failing test by not hardcoding database name

---

lib/reporter/process.rb
spec/lib/collector_spec.rb
spec/lib/reporter/process_spec.rb

This reverts commit 81abe649b79e90cca8988cffc0a373b649493621 and e7692a8d8f0c2cb20f86c26ba9f6081b47248a0b.
Adding the database labels caused the cardinality of the data set to
explode making metrics query time out.

Revert adding database label to AR connections metric

---

spec/lib/internal_metric/global_spec.rb

This is pending https://github.com/discourse/discourse/pull/27304 but
we don't have to cause builds to fail first.

DEV: Make a spec backwards compatible with stable and main

---

lib/global_reporter_demon.rb

`::Demon::Base` provides a `@logger` which `DiscoursePrometheus::GlobalReporterDemon` inherits from so let us use that instead so we get proper formatting.

DEV: Use `@logger` instead of printing to `STDERR`

---

lib/internal_metric/global.rb

Because of that [commit](https://github.com/rails/rails/commit/009c7e74117690f0dbe200188a929b345c9306c1), the `ActiveRecord::Base.postgresql_connection` method doesn’t exist anymore.
This PR addresses that issue by using what is now done in Rails: `ActiveRecord::ConnectionAdapters::PostgreSQLAdapter.new`.

DEV: Add compatibility with Rails 7.2

---

plugin.rb

Core has moved to webrick 1.8.2.
https://github.com/discourse/discourse/commit/0078f0973e90546fa73d2cb34bf8a53f80fd8f96
Follow-up to: 938680e4989bfaca4a35025fe75cf37866a0a4b2.

DEV: bump webrick to 1.8.2

---

plugin.rb

Webrick is provided by core, so we should not require a specific version here. (1.8.2 for main, Rails 7.2 will provide 1.9.0)

DEV: Add compatibility with Rails 7.2+

---

lib/internal_metric/global.rb
spec/lib/internal_metric/global_spec.rb

- **Revert "FIX: Increase interval for sequence check now that it is a slower check (#118)"**
- **Revert "FEATURE: Tweak `postgres_highest_sequence` only for int columns (#98)"**

revert sequence metric changes

---

app/jobs/scheduled/update_stats.rb
lib/internal_metric/global.rb
plugin.rb
spec/lib/internal_metric/global_spec.rb

This is a reimplementation of commit 1015d9e3 and a revert of commit 98b8d44b.
The original implementation was using the REPLACE function in the filter, which was causing the query to be very slow. For some databases, the old query ran in ~6 seconds, while this optimized one runs in ~30ms.
Unfortunately, it is still slower than the previous one that executed in ~2ms.

FEATURE: Tweak `postgres_highest_sequence` only for int columns

---

lib/collector_demon.rb
plugin.rb

This makes upgrading the webrick gem in Discourse core much easier since
we will no longer have conflicting gem versions.

DEV: Drop `webrick` gem since it is already available in Discourse core

---

lib/collector.rb
lib/internal_metric/global.rb
spec/lib/internal_metric/global_spec.rb

The Discourse application and plugins utilise the `/tmp` directory for
local storage during request and job processing. If the directory has no
space remaining, attempting to create files will fail.
Exposing the amount of space available in the directory is useful in
environments where this directory is limited in size.
See t/111786.

DEV: add tmp_dir_available_bytes metric

---

lib/internal_metric/process.rb
lib/reporter/process.rb
spec/lib/reporter/process_spec.rb

This allows us to track the CPU usage time for each process as part of
application performance monitoring efforts.

FEATURE: Add `process_cpu_seconds_total` metric

---

lib/collector.rb
lib/internal_metric/global.rb
spec/lib/internal_metric/global_spec.rb

This is a useful metric for us to track and can be used to supplement
the `sidekiq_jobs_enqueued` metric to determine if a queue is
overloaded.

FEATURE: Add `sidekiq_queue_latency_seconds` metric

---

plugin.rb

Follow-up to e1eeb65d1737c2df5963ad63fda1620daf1d1d89
This is difficult to test so I'm going to accept the risk here.

FIX: Broken `scheduled_job_ran` metric

---

lib/collector.rb

This commit drops the custom labels from the `http_queue_duration_seconds` and
`http_requests_queue_duration_seconds` metric as those labels do not add
any value to the metric. This change helps to reduce the cardinality
of the metrics which in turn helps to reduce metric storage cost.
`discourse_http_queue_duration_seconds{action="other", cache="false", content_type="other", controller="other", instance="<something>", job="<some job>", logged_in="false", node="<some node>", quantile="0.99", success="true"}`
`discourse_http_queue_duration_seconds{instance="<something>", job="<some job>", node="<some node>", quantile="0.99"}`

PERF: Drop custom labels from http queue duration metrics

---

lib/collector.rb
spec/lib/collector_spec.rb

Request queue duration happens within a smaller range of value as
compared to other request durations. Therefore, we need to tweak the
values of the buckets that better reflect the expected range of values.
See https://prometheus.io/docs/practices/histograms/#quantiles which states the following for histograms.
> Pick buckets suitable for the expected range of observed values.

FEATURE: Update hist buckets for `http_requests_queue_duration_seconds`

---

lib/collector.rb
spec/lib/collector_spec.rb

This increases the cardinality of the metrics while not really providing
meaningful information so we don't think adding this label is worth the
trade-offs.

DEV: Remove unused `cache` label for duration metrics

---

lib/internal_metric/global.rb
spec/lib/internal_metric/global_spec.rb

Discourse's Sidekiq was recently updated from 6.5.12 to 7.3.9. Since 7.2.1, `Sidekiq::Work` has replaced the third parameter of `Sidekiq::WorkSet#each`, which used to be a raw hash.

FIX: Parse Sidekiq::Work payload to extract job_name
